create table linus_user (
  id integer primary key generated by default as identity,
  user_name text not null unique,
  nickname text,
  password text not null
);

alter table spirits
  add column
    user_id integer references linus_user(id) on delete set null;